# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build UniMapping

on:
  workflow_dispatch:
    inputs:
      java-version:
        description: 'Java Version'
        required: true
        default: '21'
      thread-count:
        description: 'thread count'
        required: true
        default: '5'

jobs:
  build:
    name: Build UniMapping
    runs-on: ubuntu-latest

    steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
          - name: Grant Execute Permission for gradlew
            run: chmod +x ./gradlew
          - name: Set up JDK 21
            uses: actions/setup-java@v4.2.1
            with:
              java-version: ${{ github.event.inputs.java-version }}
              distribution: 'temurin'
              cache: gradle

          - name: Build
            run: ./gradlew build
          - name: Create Mapping
            run: |
              java -cp build/lib/FabricIntermediaryFetcher-nil.jar \
              FabricIntermediaryVersionFetcher \
              --thread-count ${{ github.event.inputs.thread-count }}
          - name: Upload Build Artifacts
            uses: actions/upload-artifact@v4
            with:
              name: intermediary-mappings
              path: intermediary_mappings/

